# YAML Parser
brew "libyaml"
# Data validation using Python type hints
brew "pydantic"
# CLI tool to build, test, debug, and deploy Serverless applications using AWS SAM
brew "aws-sam-cli"
# Official Amazon AWS command-line interface
brew "awscli"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Incredibly fast JavaScript runtime, bundler, test runner, and package manager
brew "bun"
# GNU File, Shell, and Text utilities
brew "coreutils"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Open-source GitLab command-line tool
brew "glab"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Regular expressions library
brew "oniguruma"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Network authentication protocol
brew "krb5"
# Mac App Store command-line interface
brew "mas"
# Deep clean and optimize your Mac
brew "mole"
# Open source relational database management system
brew "mysql"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"
# Node.js version manager
brew "nodenv"
# Object-relational database system
brew "postgresql@16"
# Python version management
brew "pyenv"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Persistent key-value database, with built-in net interface
brew "redis"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
# Terminal-based AI coding assistant
cask "claude-code@latest"
# OpenAI's coding agent that runs in your terminal
cask "codex"
# Brings the power of Copilot coding agent directly to your terminal
cask "copilot-cli"
cask "font-jetbrains-mono-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Tool to optimise images to a smaller size
cask "imageoptim"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Replacement for Docker Desktop
cask "orbstack"
# Mesh VPN based on WireGuard
cask "tailscale-app"
# Unpacks archive files
cask "the-unarchiver"
# Open-source BitTorrent client
cask "transmission"
# Open-source code editor
cask "visual-studio-code"
# Native desktop client for WhatsApp
cask "whatsapp"
mas "Toggl Track", id: 1291898086
