# Print the current profile, or configure, install, reload, and check it.
#
# Usage: profile <command>

profile() (
  emulate -L zsh
  local MATCH MBEGIN MEND match mbegin mend

  # Carriage return, cursor up one line, clear to end of line: rewrites the current prompt line.
  local cut=$'\r\033[1A\033[0K'
  local profile_cmd="${fg_bold[green]}profile${reset_color}"
  local profile_config_cmd="${profile_cmd}${fg_bold[green]} config${reset_color}"
  local profile_install_cmd="${profile_cmd}${fg_bold[green]} install${reset_color}"
  local working_dir_name="${WORKING_DIR/$HOME\//}"
  local name_regex='^[A-Za-z[:space:],.]{2,}$'
  local email_regex='^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
  local separator="${PROFILE_SEPARATOR:- | }"
  local marker_begin='# BEGIN PROFILE (generated by the profile plugin)'
  local marker_end='# END PROFILE'

  # Converts the editor CLI command into the corresponding Git command.
  # _profile_git_editor <command>
  _profile_git_editor() {
    case "$1" in
      atom|code|code-insiders) print -r -- "$1 --wait" ;;
      mate) print -r -- 'mate -w' ;;
      subl) print -r -- 'subl -n -w' ;;
      *) print -r -- "$1" ;;
    esac
  }

  # _profile_editor_name <command>
  _profile_editor_name() {
    case "$1" in
      atom) print -r -- 'Atom' ;;
      code|code-insiders) print -r -- 'Visual Studio Code' ;;
      nano) print -r -- 'Nano' ;;
      subl) print -r -- 'Sublime Text' ;;
      vim) print -r -- 'Vim' ;;
      *) print -r -- "$1" ;;
    esac
  }

  # _profile_log_error <message>
  _profile_log_error() {
    tput civis
    print -rn -- "${cut}${fg[red]}$1${reset_color}"
    sleep 1
    print
    print -rn -- "${reset_color}${cut}> "
    tput cnorm
  }

  # Reads, validates, and stores an input into the variable named by the first argument.
  # _profile_get_input <key> [--allow-blank]
  _profile_get_input() {
    local MATCH MBEGIN MEND match mbegin mend
    local key="$1" value
    local -i allow_blank=0
    # --allow-blank lets an empty input through so config can keep the existing value.
    [[ "$2" == --allow-blank ]] && allow_blank=1

    print -rn -- '> '
    read -r value

    case "$key" in
      name)
        # Re-prompt while the value fails the regex, unless blank is allowed and the value is empty.
        while { (( ! allow_blank )) || [[ -n "$value" ]] } && [[ ! "$value" =~ $name_regex ]]; do
          _profile_log_error 'You must specify a valid name'
          read -r value
        done
        ;;
      email)
        while { (( ! allow_blank )) || [[ -n "$value" ]] } && [[ ! "$value" =~ $email_regex ]]; do
          if [[ -z "$value" ]]; then
            _profile_log_error 'You must specify an email'
          else
            _profile_log_error "$value is not a valid email"
          fi
          read -r value
        done
        ;;
      working_dir)
        while { (( ! allow_blank )) || [[ -n "$value" ]] } && [[ ! -d "$HOME/$value" ]]; do
          _profile_log_error "$HOME/$value is not a valid directory"
          read -r value
        done
        [[ -n "$value" ]] && value="$HOME/$value"
        ;;
      editor)
        # $+commands[$value] is 1 when the editor command exists on PATH, 0 otherwise.
        while { (( ! allow_blank )) || [[ -n "$value" ]] } && (( ! $+commands[$value] )); do
          if [[ -z "$value" ]]; then
            _profile_log_error 'You must specify an editor'
          else
            _profile_log_error "$value not found"
          fi
          read -r value
        done
        ;;
    esac

    # (P) assigns through the variable whose name is held in $key.
    : ${(P)key::=$value}
  }

  # Writes the identity exports into ~/.zprofile between the generated markers,
  # preserving any hand-added content outside the fence, and syncs the matching
  # values into ~/.gitprofile (included by ~/.gitconfig).
  # _profile_write
  _profile_write() {
    local zprofile="$HOME/.zprofile"
    local -a lines block
    local key

    block=("$marker_begin")
    for key in NAME EMAIL WORKING_DIR EDITOR; do
      block+=("export $key=\"${(P)key}\"")
    done
    block+=("export GIT_EDITOR=\"$(_profile_git_editor "$EDITOR")\"")
    block+=("$marker_end")

    if [[ -f "$zprofile" ]]; then
      local -i in_block=0
      local line
      while IFS= read -r line; do
        # Drop the existing fenced block; it is rebuilt from $block above.
        [[ "$line" == "$marker_begin" ]] && { in_block=1; continue }
        [[ "$line" == "$marker_end" ]] && { in_block=0; continue }
        (( in_block )) && continue
        # Migrate legacy unfenced exports of the managed keys into the fence
        # instead of preserving them, so first-run does not duplicate/shadow them.
        [[ "$line" == 'export '(NAME|EMAIL|WORKING_DIR|EDITOR|GIT_EDITOR)'='* ]] && continue
        lines+=("$line")
      done < "$zprofile"
    fi

    print -rl -- "${block[@]}" "${lines[@]}" > "$zprofile"

    command git config --file "$HOME/.gitprofile" user.name "$NAME"
    command git config --file "$HOME/.gitprofile" user.email "$EMAIL"
    command git config --file "$HOME/.gitprofile" core.editor "$(_profile_git_editor "$EDITOR")"
  }

  case "$1" in
    config)
      local -i changed_keys=0
      local -i is_installation=0 is_reload=0
      [[ "$2" == install ]] && is_installation=1
      [[ "$2" == reload ]] && is_reload=1

      local name_msg="Name ($( (( is_installation )) && print -n 'no accent or special characters' || print -rn -- "$NAME"))"
      local email_msg="Email ($( (( is_installation )) && print -n 'to sign your commits' || print -rn -- "$EMAIL"))"
      local working_dir_msg="Working directory ($( (( is_installation )) && print -n "relative to $HOME, e.g. Developer" || print -rn -- "$working_dir_name"))"
      local editor_msg="Editor ($( (( is_installation )) && print -n 'shell command, e.g. code, nano, vim' || print -rn -- "$EDITOR"))"

      if (( ! is_installation )); then
        profile check || return 1
      fi

      if (( ! is_reload )); then
        print -r -- "${fg_bold[blue]}👤 $USER${reset_color}"
        (( is_installation )) || print -r -- '(hit ⏎ if unchanged)'
        print

        local key tmp_key msg_var
        for key in NAME EMAIL WORKING_DIR EDITOR; do
          tmp_key="${(L)key}"
          msg_var="${tmp_key}_msg"

          print -r -- "${(P)msg_var}"
          if (( is_installation )); then
            _profile_get_input "$tmp_key"
          else
            _profile_get_input "$tmp_key" --allow-blank
          fi

          if [[ -n "${(P)tmp_key}" && "${(P)tmp_key}" != "${(P)key}" ]]; then
            export "$key=${(P)tmp_key}"
            (( changed_keys++ ))
          fi
        done
      fi

      if (( changed_keys > 0 || is_installation || is_reload )); then
        _profile_write
      else
        return 0
      fi

      if (( is_reload )); then
        print -r -- "${fg_bold[blue]}$USER${reset_color}'s profile reloaded and ready for use."
      else
        print
        print -r -- "${fg_bold[blue]}$USER${reset_color}'s profile successfully configured."
      fi

      if (( is_installation )); then
        print -r -- "Type $profile_cmd to print your current configuration or $profile_config_cmd to modify it."
      fi

      print -r -- 'Run `exec zsh` to reload your shell with the new profile.'
      return 0
      ;;

    install|i)
      # Warn and require confirmation before overwriting an already-installed profile.
      if profile check >/dev/null 2>&1; then
        print -r -- "${fg[yellow]}WARNING: you already have a profile installed for the user $USER${reset_color}"
        print -rn -- 'Do you want to override the current profile? (y/N) '
        local choice
        read -r choice
        if [[ "$choice" == [yY] ]]; then
          print
          profile config install
        fi
      else
        profile config install
      fi
      return $?
      ;;

    reload)
      profile config reload
      return $?
      ;;

    check)
      if [[ ! -f "$HOME/.zprofile" ]]; then
        print -ru2 -- "${fg[red]}Missing profile for user $USER${reset_color}"
        print -ru2 -- "Type $profile_install_cmd to install a new profile"
        return 1
      elif [[ -z "$NAME" || ! "$NAME" =~ $name_regex ]] \
        || [[ -z "$EMAIL" || ! "$EMAIL" =~ $email_regex ]] \
        || [[ -z "$WORKING_DIR" || ! -d "$WORKING_DIR" ]] \
        || [[ -z "$EDITOR" ]] || (( ! $+commands[$EDITOR] )); then
        print -ru2 -- "⚠️  A profile is not installed for user $USER"
        print -ru2 -- "Type $profile_install_cmd to add a new profile"
        return 1
      fi
      return 0
      ;;

    help|-h|--help)
      print -r -- 'Usage: profile <command>'
      print
      print -r -- 'Commands:'
      print -r -- '    config      Edit the current profile.'
      print -r -- '    install     Install a new profile.'
      print -r -- '    reload      Reload the current profile.'
      print -r -- '    check       Check if the current profile is installed correctly.'
      print -r -- '    help        Show this message.'
      return 0
      ;;

    *)
      if [[ -n "$1" ]]; then
        print -ru2 -- "${fg[red]}Unknown command: $1${reset_color}"
        profile help
        return 1
      fi

      profile check || return 1

      local -a editor_lines
      # (@f) splits EDITOR on newlines into array elements.
      editor_lines=("${(@f)EDITOR}")
      local editor
      editor="$(_profile_editor_name "${editor_lines[1]%% *}")"

      print -P "%F{039}user  ${separator}%{$reset_color%}$USER"
      print -P "%F{039}name  ${separator}%{$reset_color%}$NAME"
      print -P "%F{039}email ${separator}%{$reset_color%}$EMAIL"
      print -P "%F{039}path  ${separator}%{$reset_color%}~/$working_dir_name"
      print -P "%F{039}editor${separator}%{$reset_color%}$editor"
      return 0
      ;;
  esac
)
