AllCops:
  Include:
    - Rakefile
    - config.ru
    - "**/Gemfile"
    - "**/*.gemspec"
    - "**/*.rake"
    - "**/*.rb"
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - script/**/*
    - public/**/*
    - vendor/**/*
    - "**/*.erb"

Metrics/BlockLength:
  Max: 100

Naming/MethodParameterName:
  MinNameLength: 1

Lint/AmbiguousBlockAssociation:
  Enabled: false
Layout/ClassStructure:
  Enabled: true
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    [
      "authorize",
      "desc",
      "gem",
      "has_many",
      "head",
      "print",
      "printf",
      "puts",
      "raise",
      "redirect_to",
      "render",
      "require",
      "require_relative",
      "ruby",
      "run",
      "separator",
      "source",
      "yield",
    ]
Style/MultilineMethodSignature:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/WordArray:
  Enabled: false
