#!/bin/sh

# PreToolUse guardrail (Edit|Write|MultiEdit): block writes to generated or
# auto-managed files under $HOME that would be silently overwritten, and redirect
# edits made through the agent-config symlinks to their .agents/ source. Global
# hook, so every pattern is anchored to an absolute $HOME path — it never matches
# files in projects under ~/Developer. Exit 2 blocks (stderr shown to Claude);
# any other path / missing jq fails open (exit 0). macOS; no-op without a file path.

case ":$PATH:" in
  *:/opt/homebrew/bin:*) ;;
  *) PATH="/opt/homebrew/bin:/usr/local/bin:$PATH" ;;
esac

input="$(cat)"
fp="$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.path // empty' 2>/dev/null)"
[ -n "$fp" ] || exit 0

case "$fp" in
  /*) abs="$fp" ;;
  *)  abs="$PWD/$fp" ;;
esac

deny() { printf 'Blocked by guard-managed-files: %s\n' "$1" >&2; exit 2; }

# 1. .zprofile is GENERATED by the `profile` plugin — hand-edits are lost.
[ "$abs" = "$HOME/.zprofile" ] && \
  deny "$HOME/.zprofile is generated by the profile plugin; edits are overwritten. Change the profile plugin or run 'profile install'."

# 2. Home-repo git hooks are auto-symlinked from .husky/ on shell start.
case "$abs" in
  "$HOME"/.git/hooks/*) deny "$HOME/.git/hooks/* is auto-symlinked from .husky/. Edit the matching .husky/ hook instead." ;;
esac

# 3. Agent config is single-source-of-truth in ~/.agents/ — don't edit via symlinks.
case "$abs" in
  "$HOME"/.claude/CLAUDE.md|"$HOME"/.codex/AGENTS.md|"$HOME"/.github/copilot-instructions.md)
    deny "$abs is a symlink to ~/.agents/. Edit the source under ~/.agents/ instead." ;;
  "$HOME"/.claude/rules/*|"$HOME"/.claude/skills/*|"$HOME"/.claude/hooks/*|"$HOME"/.github/instructions/*|"$HOME"/.copilot/instructions/*|"$HOME"/.codex/skills/*)
    deny "$abs resolves through a symlink to ~/.agents/. Edit the source under ~/.agents/ instead." ;;
esac

exit 0
