#!/bin/zsh

YLW="\e[33m"
GRN="\e[32m"
RED="\e[31m"
NC="\e[0m"

case $1 in
  disable)
    if [ -z $2 ]; then
      echo "${YLW}WARNING: this will disable GateKeeper globally${NC}"
      printf "Are you sure you want to continue? (y/N) "
      read -r choice
      if [[ $choice =~ [yY] ]]; then
        if (sudo spctl --master-disable >/dev/null 2>&1); then
          echo "${GRN}🔓 GateKeeper disabled globally"${NC}
        else
          echo "${RED}An error occured, please try again${NC}"
        fi
      fi
    else
      for app in "${@:2}"; do
        if (sudo xattr -r -d com.apple.quarantine $app 2>/dev/null); then
          echo "${GRN}🔓 GateKeeper disabled for ${app##*/}${NC}"
        else
          echo "${RED}Can't disable GateKeeper for ${app##*/}${NC}"
        fi
      done
    fi
    ;;

  enable)
    if (sudo spctl --master-enable >/dev/null 2>&1); then
      echo "${GRN}🔒 GateKeeper enabled globally${NC}"
    else
      echo "${RED}There was a problem enabling GateKeeper, please try again${NC}"
    fi
    ;;

  -h|--help)
    echo "Usage: gatekeeper <command>"
    echo
    echo "Commands:"
    echo -e "  disable [apps] \t Disable checks for one or multiple app, or globally if no apps are provided"
    echo -e "  enable \t\t Enable checks globally"
    ;;

  *)
    if [ $1 ]; then
      echo "${RED}Unknown command: $1${NC}"
    fi
    gatekeeper --help
    ;;
esac
