#!/bin/sh

case ":$PATH:" in
  *:/opt/homebrew/bin:*) ;;
  *) PATH="/opt/homebrew/bin:/usr/local/bin:$PATH" ;;
esac

case "${GIT_REFLOG_ACTION:-}" in
  rebase* | cherry-pick*) exit 0 ;;
esac

case "$(head -n1 "$1")" in
  \#*) exit 0 ;;
  *) commitlint --edit "$1" ;;
esac
