#!/bin/zsh

echo () {
  case $1 in
    (-t)
      rest=${*:2}
      echo "\r\033[1A\033[0K$rest"
      ;;

    (-E)
      builtin echo -E "$@"
      ;;

    (-h)
      echo "Usage: echo <string> [options]\n"
      echo "Options:"
      echo "  -n\t	Suppress trailing newline"
      echo "  -t\t	Trim the last printed line"
      echo "  -E\t	Disable interpretation of backslash-escaped characters"
      echo "  -h\t	Print this help message"
      ;;

    (*)
      builtin echo -e "$@"
      ;;
  esac
}
