#!/bin/sh

echo () {
  case $1 in
    (-t) # trim previous line
      builtin echo -e "\r\033[1A\033[0K${@:2}"
      ;;

    (-h)
      builtin echo "Usage: echo <string> [options]\n"
      builtin echo "Options:"
      builtin echo -e "   -n\t	Suppress trailing newline"
      builtin echo -e "   -e\t	Enable interpretation of backslash-escaped characters"
      builtin echo -e "   -E\t	Disable interpretation of backslash-escaped characters"
      builtin echo -e "   -t\t	Trim the last printed line"
      builtin echo -e "   -h\t	Print this help message"
      ;;

    (*)
      builtin echo $@
      ;;
  esac
}
