#!/bin/zsh

gatekeeper () (
  case $1 in
    (disable)
      if [ -z $2 ]; then
        sudo spctl --master-disable >/dev/null 2>&1
        if [ $? -eq 0 ]; then
          echo "🔓 GateKeeper disabled globally"
        else
          echo -r "An error occured, please try again"
        fi
      else
        for app in "${@:2}"; do
          app_name=$(printf "%s\n" "${app##*/}")
          sudo xattr -r -d com.apple.quarantine $app 2> /dev/null
          if [ $? -eq 0 ]; then
            echo "🔓 GateKeeper disabled for $app_name"
          else
            echo -r "Can't disable GateKeeper for $app_name"
          fi
        done
      fi
      ;;

    (enable)
      sudo spctl --master-enable >/dev/null 2>&1
      if [ $? -eq 0 ]; then
        echo "🔒 GateKeeper enabled globally"
      else
        echo -r "There was a problem enabling GateKeeper, please try again"
      fi
      ;;

    (*)
      echo "Usage: gatekeeper <command>"
      echo
      echo "Commands:"
      echo "  disable [apps] \t Disable checks for one or multiple app, or globally if no apps are provided"
      echo "  enable \t\t Enable checks globally"
      ;;
  esac
)
