#!/bin/sh

commitlint --from=HEAD --to="$(git remote)/$(git branch --show-current)" --quiet
shellcheck .husky/commit-msg .husky/pre-push .aliases .bash_profile .bashrc .profile
oxfmt --check --no-error-on-unmatched-pattern
